### PR TITLE
Fixed Issue1

### PR DESCRIPTION
**Pull request by guicamest**
Implemented interfaces properties are not properly generated.

For more information:
https://github.com/guicamest/graniteds_builder/issues/closed#issue/1

### CODE REVIEW

**Comment by fwolff** [comment]
Too old...

**Comment by guicamest** [comment]
Yea, sorry Frank. Is the feature implemented in the newer versions?
It'd be nice, i think. What do you say?

**Comment by fwolff** [comment]
No, it is not implemented in the newer versions.

To be honest, when I discovered your patch this morning, I didn't understand its purpose and my laziness decided to close it... It makes perfect sense at second sight.

**Comment by fwolff** [comment]
Patch should be implemented in the next nightly build (#252): http://www.graniteds.org/bamboo/browse/GDSEB-GDSEB.

**Comment by guicamest** [comment]
Glad to help! It's a very good job you are doing, keep it going!

**Pull request merged**
